### ISSUE TITLE
Breakdoors Command still allows SCP-096 to break doors. [Bug]

### ISSUE THREAD

**Issue by SpaceMau5e** [Rnen/AdminToolbox#10]
I have tested this on my server and found that the Breakdoors Command did not stop SCP-096 from breaking doors while enraged. I am assuming that you meant this form of breaking doors behind the commands discription.

I used the command in the RA console and tried it in both the BD (User) True/False and the Breakdoors (User) True/False formats and both failed to work.

**Comment by Rnen** [comment]
Meanwhile stopping 096 from breaking doors never was the intention, it might be a feature in the future. For now its really hard to check if 096 is enraged or not, so the command have no effect on 096 players
