### ISSUE TITLE
i dont know 2

### ISSUE THREAD

**Issue by Tamago4a** [Rnen/AdminToolbox#100]
### Version (please complete the following information):
 - Smod Version: last 3.5.1 - H
 - AdminToolbox Version: last v.1.3.8-1

![Безымянный](https://user-images.githubusercontent.com/47304666/65778898-6b471f80-e14f-11e9-936d-28fddf98093f.png)
![Безымянный1](https://user-images.githubusercontent.com/47304666/65778903-6e421000-e14f-11e9-8fe6-746bc3ba76c8.png)
![Безымянный2](https://user-images.githubusercontent.com/47304666/65778906-71d59700-e14f-11e9-9aae-a8c95442f300.png)

**Comment by Rnen** [comment]
Try my latest pre-release, this might be fixed there.
https://github.com/Rnen/AdminToolbox/releases/tag/1.3.8-10
