### ISSUE TITLE
Low ram?

### ISSUE THREAD

**Issue by LucarioJapans** [Rnen/AdminToolbox#102]
### Version (please complete the following information):
 - Smod Version: 3.5.0
 - AdminToolbox Version: Latest.

### Describe the bug
I upload AdminToolbox to my server, And my server crashes because of low amount of ram. I don't think AdminToolbox needs so much ram, Then why does it crash? Even if admintoolbox is the only plugin it still crashes. And I have like 20 plugins and it's fine without AdminToolbox. What to do?

### To Reproduce
For me just upload and start server.

### Expected behavior
Normally working plugin, Not crashing server.

### Additional text
N/A

**Comment by Rnen** [comment]
Please specify exact version, not "Latest"
Also, i'd recommend trying my latest pre-release
https://github.com/Rnen/AdminToolbox/releases/tag/1.3.8-10
