### ISSUE TITLE
Infinite ragdolls 

### ISSUE THREAD

**Issue by Nikitach123hack** [Rnen/AdminToolbox#107]
### Version (please complete the following information):
 - Smod Version:
 - AdminToolbox Version: 

### Describe the bug
When I hit a person with one bullet, it doesn't matter how much damage I do. With him falls his corpse, and the player does not die, he continues to be active. And I can't kill anyone, not just me and all the players. What should I do?

**Comment by Rnen** [comment]
This issue is not related to this plugin.
