### ISSUE TITLE
Role * (ClassID) Doesn't Work

### ISSUE THREAD

**Issue by Mozeman** [Rnen/AdminToolbox#12]
### Describe the bug
When attempting to use the `role` command for ` * ` all players, it doesn't seem to work although saying "Done! Affected # of players 

### To Reproduce
1. Go to 'Remote Admin'
2. Use `role * (classID)`

### Expected behavior
Should change role of all players.

### Screenshots
No screenshot(s) available.

### Desktop (please complete the following information):
 - Smod Version: 3.1.1
 - AdminToolbox Version: 1.2

### Additional context
No Additional context.

**Comment by Mozeman** [comment]
I'm not too familiar with github so sorry if there is an edit feature,

I'd like to just add that in the AdminToolbox Version 1.2 changelog it was mentioned: 
`Fixed: role command should work now`

I hadn't had any issues with `role` in the previous version, 1.1

**Comment by Rnen** [comment]
Dont worry about adding comments instead of editing, its actually better so i know what changed 😅 
I think the problem is i just forgot to update the `*` part of the script to the newer setrole api

**Comment by Rnen** [comment]
![](https://i.imgur.com/oAs99zb.jpg)

Probally that first bool thats breaking it, will patch it later

**Comment by Rnen** [comment]
Should be working in the next release of Admintoolbox.
