### ISSUE TITLE
Tie warp points into ROOMIDs

### ISSUE THREAD

**Issue by slyguy65** [Rnen/AdminToolbox#13]
Grover made "tproom player roomid" command.

He said roomids may not be a thing much longer, but the POS is just too cumbersome to be useful and the warp points while good in concept serve little practical use since they reset each round.

Maybe for now have a way to tie warp points into the room ID's so we can just say "topsite" room ID is warp point "ci spawn", or "HC_TESLA_B" into something shortened and easier to remember.

May not be worth it but the main goal im looking for is a simplified way of TP'ing around this is this only way i can think of to make it easier.

**Comment by Rnen** [comment]
Since the smod devs added `tproom` to smod, this feature request is depricated
