### ISSUE TITLE
Set SCP as Bot

### ISSUE THREAD

**Issue by ThanosAtha** [Rnen/AdminToolbox#131]

**Comment by ThanosAtha** [comment]
can we add a bot in the SCP role, or just show all players in a SCP's radar??? It's kinda boring if u don't know where is anyone.....!

**Comment by Rnen** [comment]
As this plugin is based on SMod, and SMod isn't developed anymore, no new features will come to the plugin.
If this gets updated, it will only be for critical issues regarding stability.
