### ISSUE TITLE
Role Damage types and Disabling role damage commands

### ISSUE THREAD

**Issue by Redd-king** [Rnen/AdminToolbox#14]
### Is your feature request related to a problem? Please describe.
I hate it when tutorials can kill SCPs on my server when SCPs can't kill them. (Custom role thing)

### Describe the solution you'd like
Add a config option that allows [ClassID1] to not damage [ClassID2] and add the damage type options for all roles. [ClassID] can't take fall damge. [ClassID] can't be hurt by the logister. Stuff like that.

### Describe alternatives you've considered
I don't have anything to put here.

### Additional context
Nothing extra.

**Comment by Rnen** [comment]
Added the `[ClassID1] to not damage [ClassID2]` to the upcoming update.
If you still wish the other feature(s), please post a seperate suggestion :slightly_smiling_face:
