### ISSUE TITLE
Force decontamination procedure

### ISSUE THREAD

**Issue by ArkhamKn1ght** [Rnen/AdminToolbox#17]
### Is your feature request related to a problem? Please describe.
My RP server lacks a command which forces decontamination procedure . 

### Describe the solution you'd like
Somethink like this : 
forcedecontamination 0.5/1/5/10 where every number reproduces his own sound file : 
0.5 - decontamination in 30 seconds
1 - decontamination in 1 minute
5 - decontamination in 5 minutes
10 - decontamination in 10 minutes

### Describe alternatives you've considered
-
### Additional context
-

**Comment by Rnen** [comment]
I've added the API to Smod, will become a command for AdminToolbox for major release

**Comment by Rnen** [comment]
Will re-open when feature is possible to implement.
