### ISSUE TITLE
lockdown for only 1 door

### ISSUE THREAD

**Issue by ArkhamKn1ght** [Rnen/AdminToolbox#21]
### Is your feature request related to a problem? Please describe.
Add a command which lockdowns only 1 door

### Describe the solution you'd like
Sometimes it need to imitate broken door. This command solve that problem

**Comment by Rnen** [comment]
## What
Do you mean like locking 1 spesific door?
That might be difficult

**Comment by ArkhamKn1ght** [comment]
@rnen I do

**Comment by Rnen** [comment]
Adding it to the [Trello Board](https://trello.com/b/NnNBzSX2/scpsl-admintoolbox-plugin)
![image](https://user-images.githubusercontent.com/10668020/41672592-976f3758-74ba-11e8-8eab-350dd00887c6.png)

**Comment by Rnen** [comment]
Since i had the developers add it to the game, this suggestion is now depricated
