### ISSUE TITLE
Roundtimer

### ISSUE THREAD

**Issue by Redd-king** [Rnen/AdminToolbox#29]
### Is your feature request related to a problem? Please describe.
I want a round to stay active for X amount of time and not end when a team completes the objective.

### Describe the solution you'd like.
Add a config command that works like round lock, but turns off after X amount of time happens.

**Comment by Rnen** [comment]
This sounds more like a idea for a seperate plugin/gamemode manager plugin
Sorry if this is inconvenient. :cry:
