### ISSUE TITLE
Suggestion: Connect/Disconnect log

### ISSUE THREAD

**Issue by REALMWTH** [Rnen/AdminToolbox#3]
### Is your feature request related to a problem? Please describe.
No, I just wanted to suggest add new feature to admintoolbox.

### Describe the solution you'd like
It would be awesome to add players connection/disconnection log to its own txt file.
So we could track hackers and griefers after they leave server.

### Describe alternatives you've considered
An alternative you could create just a console output...

### Additional context
nothing to do here

**Comment by Rnen** [comment]
I am actually looking into having the plugin generate files, like stats for each player (kills, teamkills, deaths, playtime).
Untill i've sorted the file thing, i might just add this as an optional config so it displays in the srver console

**Comment by realmbmc** [comment]
Actually I've found that server generates its own log files for each round in ServerLogs folder with connection and disconnection log.
Example: (ConnectionUpdate:12:57 PM) Player connected & verified. IP: xxx | SteamID: xxx | Nickname: xxx
