### ISSUE TITLE
Detain Player Command [Suggestion]

### ISSUE THREAD

**Issue by SpaceMau5e** [Rnen/AdminToolbox#43]
Is it possible to add a disarm command to your plugin? Because I run a FF on server and want to punish players by stripping them of gear instead of making the spectators.

**Comment by Rnen** [comment]
I coult possibly create a command to empty an inventory :thinking: Not sure if i'd make it so items just dissapear or if they drop to the ground :grin: 
Probally would be easier just to make them dissapear tho

**Comment by Rnen** [comment]
Oh, *am already working on a jail command that will set players to tutorial in one of the topsite towers (they cant get out or shoot out)

**Comment by SpaceMau5e** [comment]
Just want to ask, but awhile ago I think Dankrushen mentioned that there was an API for players being detained. Could you just make that read true or false and detain or release the player?

**Comment by Rnen** [comment]
Afaik the player.IsCuffed()  is a read-only bool, so i cannot interact with it in any way, only check the player's current state
