### ISSUE TITLE
Separate txt log file for kill logs

### ISSUE THREAD

**Issue by realmbmc** [Rnen/AdminToolbox#5]
I suggest you to create separate txt log file for kill logs so I can parse data using my own Discord bot.
With formatting like:
time;killed_player;killer_player;teamkill/kill;config_id

Similar ban log would be great too:
With formatting like:
time_of_ban;time_to_unban;nickname;steamid;ip

**Comment by Rnen** [comment]
Funny part is, kill log file is almost done already, tho if you currently enable it it gives you a big ass error
![image](https://user-images.githubusercontent.com/10668020/41156517-8819b27a-6b22-11e8-9e8b-c9627e887ea2.png)

**Comment by realmbmc** [comment]
Yeah but formatting is the most important thing, that would be great if you will use one character as divider so I can easilly parse the text logs.
