### ISSUE TITLE
Reference to warpVectors is lost at the start

### ISSUE THREAD

**Issue by secondfry** [Rnen/AdminToolbox#51]
Here you define two separate dictionaries.
https://github.com/Rnen/AdminToolbox/blob/master/AdminToolbox/AdminToolbox/AdminToolbox.cs#L31-L42

Here you lose reference to `warpVectors` forever.
https://github.com/Rnen/AdminToolbox/blob/master/AdminToolbox/AdminToolbox/AdminToolbox.cs#L94

After that each modification of `warpVectors` is actually modification of `presetWarps`.

Example:
https://repl.it/repls/ImprobableVapidWebmaster

**Comment by secondfry** [comment]
I think you've meant to ```csharp
AdminToolbox.warpVectors = new Dictionary<string, Vector> (AdminToolbox.presetWarp);
```

**Comment by Rnen** [comment]
Not sure what you mean how
```cs
warpVectors = presetWarps;
// is different from
AdminToolbox.warpVectors = new Dictionary<string, Vector> (AdminToolbox.presetWarp);
```
please elaborate

**Comment by secondfry** [comment]
Check the REPL I've provided: https://repl.it/repls/ImprobableVapidWebmaster.
Basically you are losing pointer to variable and both variable names then point to one variable in memory.

**Comment by Rnen** [comment]
Oh right *derp*, now i see what you mean :man_facepalming: 

How did i miss that :joy: 
Fixing it in the next update
