### ISSUE TITLE
Turn off role damage block at round end

### ISSUE THREAD

**Issue by Redd-king** [Rnen/AdminToolbox#52]
### Is your feature request related to a problem? Please describe.
I always wanted people to try and have an all out deathmatch at the end of the round for fun.

### Describe the solution you'd like
Allow a command that turns off all role damage blockers at the end of the round _and possibly teleport them to a certain room of choice upon doing so, like the surface, 079's room, etc.

**Comment by Rnen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Config to turn off RoleDamages blocked damage on round end](https://trello.com/c/O7nf27pT/38-config-to-turn-off-roledamages-blocked-damage-on-round-end)
