### ISSUE TITLE
Single Door Open/Close Command [Suggestion]

### ISSUE THREAD

**Issue by SpaceMau5e** [Rnen/AdminToolbox#6]
I suggest adding a command that allows the opening of 1 door at a time to make it easier for players trapped in rooms that require keycards to be freed without causing every door in the facility to open.

i.e. Open 914s containment door to free the trapped player so the game can continue and not be delayed until light containment decontamination. Or open the doors to SCP-079s containment so the SCPs can kill the player hiding and prolong the game.

**Comment by Rnen** [comment]
Currently in the works, will make a command to open the closest door to a player, since getting where a player is looking is very hard.

**Comment by Rnen** [comment]
So here's how its gonna work:
 - Command to open/close closest door
 - Command to open/close all blast doors (big doors)
 - Command to open/close all small doors

**Comment by Rnen** [comment]
Since i had the devs add this to the game, this feature request is now depricated
