### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by ShuterLive** [Rnen/AdminToolbox#65]
Plugin was working fine to time i have reinstall SCP.
When i start server i got message in multiadmin "Failed to load DLL [PLACE WHERE DLL IS IN SM PLUGINS] , is it up to date?
It's problem from game or what?

**Comment by Rnen** [comment]
I released a test-release in the discord, this should work fine
Releases here on GitHub are for the old version.
New release as soon as test-release is confirmed to be stable

https://discord.gg/RGf6Y64
