### ISSUE TITLE
ATBAN usage

### ISSUE THREAD

**Issue by squidass** [Rnen/AdminToolbox#68]
## Question: 
Could someone please help me with ATBAN command. I've tried to use it, but I can't correctly understand how to use it.

![20180928005253_1](https://user-images.githubusercontent.com/42285309/46304456-69d42d00-c5b7-11e8-8844-7b1933643176.jpg)

I don't understand what is [NAME] (or PlayerName in ReadMe.md). As you can see I've tried to ban a cheater which left the game, but it didn't work for me and ban list in folder of server didn't changed at all.
Thanks in advance!

**Comment by squidass** [comment]
![dasd](https://user-images.githubusercontent.com/42285309/46305333-cfc1b400-c5b9-11e8-94f4-543bc675b704.PNG)
![fdfd](https://user-images.githubusercontent.com/42285309/46305335-d0f2e100-c5b9-11e8-9772-6ca3ee28fd7a.PNG)

Is that right?

**Comment by lordofkhaos** [comment]
Check your banfile, if everything is correct, then yes

**Comment by squidass** [comment]
![default](https://user-images.githubusercontent.com/42285309/46305628-9fc6e080-c5ba-11e8-99dd-fd2a56a37d2b.PNG)

Yep! There he is! 
But what about this image
![fdfd](https://user-images.githubusercontent.com/42285309/46305665-be2cdc00-c5ba-11e8-9dfb-e8b4c9d2a2c2.PNG)
where squidass is banned player's name?

**Comment by lordofkhaos** [comment]
Might be a bug ¯\_(ツ)_/¯

**Comment by squidass** [comment]
Ok then. 
Thank you very much! 
Should I write an issue with a bug tag?)

**Comment by lordofkhaos** [comment]
No need, I already messaged Rnen about it https://github.com/Rnen/AdminToolbox/blob/master/AdminToolbox/AdminToolbox/Commands/ATBanCommand.cs#L58

**Comment by Rnen** [comment]
Issue fixed in latest [release.](https://github.com/Rnen/AdminToolbox/releases)
