### ISSUE TITLE
The plugin didn't work

### ISSUE THREAD

**Issue by Pro845627** [Rnen/AdminToolbox#69]
When I open my server,it always shows:
Failed to create instance of plugin AdminToolbox.AdminToolbox[D:/Steam/steamapps/common/SCP Secret Laboratory Dedicated Server/SCPSL_Data/../sm_plugins/AdminToolbox.dll]
Please tell me why!!!

**Comment by Rnen** [comment]
Most likely wrong version, try the newest pre-release i put in the [#admintoolbox](https://discord.gg/n8Xc9cp) channel on discord.
