### ISSUE TITLE
SCP-096 Rage Time Editor

### ISSUE THREAD

**Issue by Redd-king** [Rnen/AdminToolbox#7]
### Is your feature request related to a problem? Please describe.
Nope. It is related to a pre-existing bug in the game itself, however.

### Describe the solution you'd like
If possible, you could change certain packets the server receives for 096's rage timer and make them infinite or to a changed value the owner sets themselves.

### Describe alternatives you've considered
I don't have a better way of doing this other than the packets, but then again, I am not a plug in developer. I know it is possible.

**Comment by Rnen** [comment]
For now this is incredibly hard to do, so I'll put the suggestion on ice untill it becomes more do-able
