### ISSUE TITLE
Feature: Add better ghostmode commands

### ISSUE THREAD

**Issue by Redd-king** [Rnen/AdminToolbox#71]
Add the ability to customize if the players ghostmode disables when talking or shooting and if they are visible to spectators or certain teamID values.

**Comment by Rnen** [comment]
Did you mean disables permamently when talking/shooting?
because the current command works this this

`ghost (someplayer) (bool: enable/disable) (bool: visibleToSpectators) (bool: visible while talking)`

**Comment by Rnen** [comment]
So for example 
`ghost Evan true false true`

**Comment by Rnen** [comment]
Reopen a new issue if this didnt answer the current one.
