### ISSUE TITLE
Server crashes when you go into jail then overwatch then leave overwatch again.

### ISSUE THREAD

**Issue by Mans334** [Rnen/AdminToolbox#72]
### Version (please complete the following information):
 - Smod Version: 3.2.0
 - AdminToolbox Version: Temp-Release for Smod 3.2.0 from Discord

### Describe the bug
The bug completely crashes the Server. Everyone is at a standstill and you need to completely kill the console (screen session) to restart the server.

### To Reproduce
1. Jail yourself
2. Go into Overwatch using the Remote Admin Console
3. Leave Overwatch using the Remote Admins Console

### Expected behavior
Expected was that you'd get into jail again after leaving Overwatch.

### Additional text
Unjailing while in Overwatch and then leaving Overwatch does not crash the server.

I'm using Linux Debian 9 Stretch with MultiAdmin 2.1.3 from the Discord running in a screen with mono. Usually works fine. I know its a bit of an experimental setup. If you need more info feel free to contact me on Discord Mans334#5742 .

Serverlog of the exception is appended. So is the logs SCPDiscord gives me before the server dies (this is just a small snippet of the message flood but its the only message)

[exception.txt](https://github.com/Rnen/AdminToolbox/files/2706158/exception.txt)

![2018-12-23 18_16_34-window](https://user-images.githubusercontent.com/1353268/50386039-ad829280-06df-11e9-9505-71a5c5b1b904.png)

**Comment by Rnen** [comment]
Belive this has been resolved in the newest release. Please open a new issue if the bug persists
