### ISSUE TITLE
[Feature Request] Better Setgroup

### ISSUE THREAD

**Issue by PintsizedSix40** [Rnen/AdminToolbox#73]
Setgroup is pretty limited at the moment and cannot run from the console. It would be great if you could implement a better setgroup command that can be run from the console & remote admin and accepts usernames & SteamIDs. Thank you.

**Comment by Rnen** [comment]
Just like to mention, it **can** actually be run from the console, if you add `/` in front of the command

**Comment by Rnen** [comment]
Now supported by the main game via Permission Manager (`pm` command)
