### ISSUE TITLE
sm_enable_ghostmode makes everyone invisible

### ISSUE THREAD

**Issue by PintsizedSix40** [Rnen/AdminToolbox#76]
Enabling sm_enable_ghostmode spawns everyone in as a ghost, but disabling it stops you from running the ghost command. It would be cool if this got fixed since it seems like a pretty useful and fun command.

**Comment by Rnen** [comment]
Unfortunately, this is a bug with **SMod**, not AdminToolbox :cry: 
I'd recommend creating a issue over at the [SMod Github](https://github.com/Grover-c13/Smod2)

**Comment by PintsizedSix40** [comment]
Crap, I did make an issue there, but I marked it as closed.
