### ISSUE TITLE
Role command doesn't work

### ISSUE THREAD

**Issue by Redd-king** [Rnen/AdminToolbox#8]
### Describe the bug
The "role" command just doesn't work.

### To Reproduce
1. Go to the server console.
2. type in role [PLAYER] [CLASSID]
3. See it say it changed, but nothing actually happened.

### Expected behavior
I expected the player I changed to become the role I assigned to them and do it without respawning or with no new items.

### Desktop (please complete the following information):
 - Smod Version: 3.1.0

### Additional context
"tutorial [PLAYER]" still works. It works as if role was used to do it, but it's a different command.

**Comment by Rnen** [comment]
Should work in the newest version.
