### ISSUE TITLE
Server crashes when changing roles

### ISSUE THREAD

**Issue by agent188** [Rnen/AdminToolbox#83]
Server crashes when changing roles.

Try changing your role through the console a couple of times (role [player id] [class id]) when suddenly after that the server crashes.

**Comment by Rnen** [comment]
What SMod version is the server using?

**Comment by agent188** [comment]
3.3.0

**Comment by Rnen** [comment]
Should be resolved in latest [pre-release[(https://github.com/Rnen/AdminToolbox/blob/master/AdminToolbox/AdminToolbox/API/ATWeb.cs#L48-L49).
Reopen if problem persists
