### ISSUE TITLE
ATBAN reason parameter is broken, cannot handle spaces

### ISSUE THREAD

**Issue by PatPeter** [Rnen/AdminToolbox#84]
### Version (please complete the following information):
 - Smod Version: 3.2.2
 - AdminToolbox Version: 1.3.8-5

### Describe the bug
I typed the following on my server:

`atban PatPeter 76561297984998697 1440 "He's a badmin"`

It resulted in the following ban line:

`PatPeter;76561297984998697;636891604550120450;"He's;|UGA|PatPeter;636890740550120450`

### To Reproduce
1. Type `atban YourName SteamID 1440 "Reason in quotes here"`
2. Open SteamIdBans.txt and scroll to the bottom.
3. You will not see the entire reason for your ban.

### Expected behavior
The ban file should contain the ban reason with spaces.

### Additional text
Here's the code I use in my `callvote` plugin to get quoted command parameters without the command itself.

```
					string[] quotedArgs = Regex.Matches(string.Join(" ", ev.Command), "[^\\s\"\']+|\"([^\"]*)\"|\'([^\']*)\'")
						.Cast<Match>()
						.Select(m => m.Value)
						.ToArray()
						.Skip(1)
						.ToArray();
```

However, this code does not remove the quotations so you'll have to do a trim on the result.

**Comment by Rnen** [comment]
Yeah... that would be me doing an oopsie
![image](https://user-images.githubusercontent.com/10668020/54899768-3670bc00-4ed1-11e9-9d36-a68bba7620cf.png)

While its supposed to be
![image](https://user-images.githubusercontent.com/10668020/54899828-76d03a00-4ed1-11e9-9f0a-28e0c49f3344.png)

**Comment by Rnen** [comment]
Or actually, this should properly do it
![image](https://user-images.githubusercontent.com/10668020/54900093-518ffb80-4ed2-11e9-99fb-f401cf7c36cd.png)
