### ISSUE TITLE
Commands do not work on Admintoolbox v.1.3.8-5, incompatible with Smod 3.2.2?

### ISSUE THREAD

**Issue by PatPeter** [Rnen/AdminToolbox#85]
### Version (please complete the following information):
 - Smod Version: 1.3.8-5
 - AdminToolbox Version: 3.2.2

### Describe the bug
It seems no commands work if using 1.3.8-5 on Smod 3.2.2. If this is the case, could there be a minimum compatibility notice in the Release information?

### To Reproduce
1. Type any command in admin console.
2. View the output.

![Command fails](https://i.imgur.com/wBIwWMb.png)

### Expected behavior
The commands should work.

### Additional text
None.

**Comment by Rnen** [comment]
Ah yes sorry, this would be SMod changing the Usergroup framework between SMod 3.2.2 and 3.0.0

**Comment by Rnen** [comment]
Oh, and i updated the releases with a big header

**Comment by PatPeter** [comment]
Thank you!!!
