### ISSUE TITLE
White list of commands does not work

### ISSUE THREAD

**Issue by agent188** [Rnen/AdminToolbox#88]
### Version (please complete the following information):
 - Smod Version: 3.4.0-A
 - AdminToolbox Version: 1.3.8-5

### Describe the bug
In the config set up a white list of certain commands under the group, but it does not work

### To Reproduce
1. Add admintoolbox_warp_whitelist to the server config: * role *
2. Go to your server
3. We write the command "warp" in RA
4. Result

### Expected behavior
Expectation: the team works for my role

![image](https://user-images.githubusercontent.com/41228098/57079487-18308400-6cf9-11e9-9ebf-388cb9249afc.png)
![image](https://user-images.githubusercontent.com/41228098/57079499-1ff02880-6cf9-11e9-9d70-8690d2c36e3b.png)

I translated using google translator, I apologize for my English

**Comment by Rnen** [comment]
The message "Unknown command! (Not whitelisted to run server commands)" is from [SMod](https://github.com/Grover-c13/Smod2/wiki/Config-additions#administration--gameplay), not AdminToolbox.

**Comment by agent188** [comment]
The bug is reproduced with bypass_server_command_whitelist: true

**Comment by Rnen** [comment]
Then i suggest creating an issue over at:
https://github.com/Grover-c13/Smod2/issues

Then refrence **this** issue there, by typing
Rnen/AdminToolbox#88
