### ISSUE TITLE
Warp saved by the old coordinates

### ISSUE THREAD

**Issue by Tamago4a** [Rnen/AdminToolbox#91]
Warp saved by the old coordinates. When the restart of the round occurs, the arrangement of the rooms changes. When teleporting to warp, I can render in space or be inside some other room, or be outside the walls. This is definitely an interesting feature and you can even make a separate function to jump through the wall. But this function should work fine. Standard warpes (for example, mtf, grass etc) receive normal coordinates for each round.

#ADMINTOOLBOX
#ADMINTOOLBOX - GENERAL SETTINGS
admintoolbox_enable: true
admintoolbox_colors: true
atb_disable_networking: false
admintoolbox_tracking: false
admintoolbox_round_info: true
admintoolbox_player_join_info_extended: true
admintoolbox_player_join_info: true
#ADMINTOOLBOX - DAMAGE SETTINGS
admintoolbox_tutorial_dmg_allowed: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
admintoolbox_Round_damageMultiplier: 1
admintoolbox_endedRound_damageMultiplier: 1
admintoolbox_decontamination_damagemultiplier: 1
admintoolbox_friendlyfire_damagemultiplier: 0.5
admintoolbox_block_role_damage: 2:2
#ADMINTOOLBOX - INFO SETTINGS
admintoolbox_info_player_join: true
#ADMINTOOLBOX - INTERCOM SETTINGS
admintoolbox_intercom_whitelist: owner0:120:1,admin0:120:1,admin1:120:1,admin2:120:1,admin3:120:1,admin4:120:1,admin5:120:1,admin6:120:1,admin7:120:1,admin8:120:1,admin9:120:1,admin10:120:1,admin11:120:1,admin12:120:1,admin13:120:1,admin14:120:1,admin15:120:1,admin16:120:1,admin17:120:1,admin18:120:1,admin19:120:1,admin20:120:1,moderator:120:1,moderator0:120:1,moderator1:120:1,moderator2:120:1,moderator3:120:1,moderator4:120:1,moderator5:120:1,moderator6:120:1,moderator7:120:1,moderator8:120:1,moderator9:120:1,moderator10:120:1,moderator11:120:1,moderator12:120:1,moderator13:120:1,moderator14:120:1,moderator15:120:1,moderator16:120:1,moderator17:120:1,moderator18:120:1,moderator19:120:1,moderator20:120:1,bum0:120:1,bum1:120:1,bum2:120:1,bum3:120:1,bum4:120:1,bum5:120:1,bum6:120:1,bum7:120:1,bum8:120:1,bum9:120:1,bum10:120:1,bum11:120:1,bum12:120:1,bum13:120:1,bum14:120:1,bum15:120:1,bum16:120:1,bum17:120:1,bum18:120:1,bum19:120:1,bum20:120:1,bum21:120:1,bum22:120:1,bum23:120:1,bum24:120:1,bum25:120:1
#admintoolbox_intercom_steamid_blacklist
admintoolbox_intercomlock: false
#ADMINTOOLBOX - LOGFILE SETTINGS
admintoolbox_log_teamkills: true
admintoolbox_log_kills: false
admintoolbox_log_commands: true
admintoolbox_log_damage: false
admintoolbox_folder_path: %Appdata%\Roaming\SCP Secret Laboratory\
admintoolbox_stats_unified: false
admintoolbox_logremover_hours_old: 24
#ADMINTOOLBOX - DEBUG SETTINGS
admintoolbox_debug_damagetypes: 5,11,12,13,14,15,16
admintoolbox_debug_player_damage: false
admintoolbox_debug_friendly_damage: false
admintoolbox_debug_player_kill: false
admintoolbox_debug_scp_and_self_killed: false
admintoolbox_debug_friendly_kill: true
#ADMINTOOLBOX - OTHER SETTINGS
admintoolbox_roledamageblock_onroundend: false
admintoolbox_intercomtransmit_text: $player пиздит хуйню по Интеркому. Осталось_
admintoolbox_intercomready_text: Зажми Q и спиздани на весь комплекс хуйню
admintoolbox_intercomrestart_text: Жди теперь уёбище ебаное. Осталось ждать_

**Comment by Rnen** [comment]
Not sure what you are asking :thinking:

**Comment by Tamago4a** [comment]
Test the created warps after restarting the round and you will understand everything yourself.

**Comment by Rnen** [comment]
Warps below surface is not supported due to position changes.
