### ISSUE TITLE
Please update the settings list

### ISSUE THREAD

**Issue by Tamago4a** [Rnen/AdminToolbox#97]
admintoolbox_roledamageblock_onroundend
admintoolbox_intercomtransmit_text
admintoolbox_intercomready_text
admintoolbox_intercomrestart_text
admintoolbox_friendlyfire_damagemultiplier
admintoolbox_(insertCommandNameHere)_whitelist
admintoolbox_master_whitelist

Please change according to the standard
atb_disable_networking >>> admintoolbox_disable_networking

**Comment by Rnen** [comment]
![image](https://user-images.githubusercontent.com/10668020/66324082-21b3bd00-e925-11e9-9cec-e4fed88e056d.png)
Code already supports both formats.
https://github.com/Rnen/AdminToolbox/blob/master/AdminToolbox/AdminToolbox/API/ATWeb.cs#L48-L49

**Comment by Tamago4a** [comment]
No settings appeared in the Intercom Settings block.
https://github.com/Rnen/AdminToolbox/wiki/Configuration-Documentation#intercom-settings

admintoolbox_intercomtransmit_text: 
admintoolbox_intercomready_text: 
admintoolbox_intercomrestart_text:

**Comment by Rnen** [comment]
And just to mention it, anyone can contribute to the Wiki. So if there is a mistake/something is missing, please do help :smile:

**Comment by Tamago4a** [comment]
ok. I did not know.
