### ISSUE TITLE
i dont know

### ISSUE THREAD

**Issue by Tamago4a** [Rnen/AdminToolbox#99]
### Version (please complete the following information):
 - Smod Version: last
 - AdminToolbox Version: last

### Describe the bug
i dont know

### To Reproduce
1. i dont know

### Expected behavior
i dont know

### Additional text
i dont know
![Безымянный](https://user-images.githubusercontent.com/47304666/64475390-ec337c80-d18a-11e9-8c86-df25f6c3e85c.png)

**Comment by Rnen** [comment]
This might be fixed in my latest pre-release **1.3.8-10**
https://github.com/Rnen/AdminToolbox/releases/tag/1.3.8-10
